/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Conexiones.GenerarPDF;
import Conexiones.conexion;
import Procedimientos.DPaciente;
import Procedimientos.Paciente;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Jesús Mendoza
 */
public class DatosPaciente extends javax.swing.JFrame {

    /**
     * Creates new form BPaciente
     */
    
    public DatosPaciente() {
        initComponents();
        inicComp();
    }

    public void inicComp(){
        conexion cn = new conexion();
        ArrayList lista = new ArrayList();
        Paciente dts = new Paciente();
        Doctor doc = new Doctor();
        String p = doc.pac;
        dts.setNombre(p);    
        lista = cn.DPac(dts);

        DPaciente dp = (DPaciente)lista.get(0);
        lblNombre.setText("Paciente: " + dp.getNombre());
        lblEdad.setText("Edad: " + dp.getEdad());
        lblIMC.setText("IMC: " + dp.getImc());
        lblPP.setText("Personales Patológicos: " + dp.getPersPat());
        lblNP.setText("No Patológicos: " + dp.getNoPat());
        lblFam.setText("Familiares: " + dp.getFam());
        lblMQ.setText("Médico Quirúrgico: " + dp.getMedQui());
        lblPad.setText("Padecimiento: " + dp.getPad());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblMQ = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblEdad = new javax.swing.JLabel();
        lblIMC = new javax.swing.JLabel();
        lblPad = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnImprimir = new javax.swing.JButton();
        lblPP = new javax.swing.JLabel();
        lblNP = new javax.swing.JLabel();
        lblFam = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 500));

        jPanel1.setBackground(new java.awt.Color(118, 219, 209));

        jPanel2.setBackground(new java.awt.Color(236, 244, 243));

        lblMQ.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        lblMQ.setText("Médico Quirúrgico:");

        lblEdad.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        lblEdad.setText("Edad:");

        lblIMC.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        lblIMC.setText("IMC:");

        lblPad.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        lblPad.setText("Padecimiento:");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        jLabel4.setText("Antecedentes");

        btnImprimir.setBackground(new java.awt.Color(85, 81, 81));
        btnImprimir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnImprimir.setForeground(new java.awt.Color(255, 255, 255));
        btnImprimir.setText("IMPRIMIR");
        btnImprimir.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        btnImprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnImprimir.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnImprimirFocusGained(evt);
            }
        });
        btnImprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnImprimirMouseClicked(evt);
            }
        });
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        btnImprimir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnImprimirKeyPressed(evt);
            }
        });

        lblPP.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        lblPP.setText("Personales Patológicos:");

        lblNP.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        lblNP.setText("No Patológicos:");

        lblFam.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        lblFam.setText("Familiares:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPad, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIMC, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEdad, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPP, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNP, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFam, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMQ, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(lblEdad)
                .addGap(18, 18, 18)
                .addComponent(lblIMC)
                .addGap(18, 18, 18)
                .addComponent(lblPad)
                .addGap(15, 15, 15)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(lblPP)
                .addGap(18, 18, 18)
                .addComponent(lblNP)
                .addGap(18, 18, 18)
                .addComponent(lblFam)
                .addGap(18, 18, 18)
                .addComponent(lblMQ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        lblNombre.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        lblNombre.setText("Paciente:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombre)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addComponent(lblNombre)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImprimirFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnImprimirFocusGained

    }//GEN-LAST:event_btnImprimirFocusGained

    private void btnImprimirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImprimirMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImprimirMouseClicked

    public static String ruta;
    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed

         JFileChooser dlg = new JFileChooser();
         int option = dlg.showSaveDialog(this);
        
         if(option == JFileChooser.APPROVE_OPTION){
             File f = dlg.getSelectedFile();
             ruta = f.toString();
         }
        
         GenerarPDF pdf = new GenerarPDF();     
         String nombre = lblNombre.getText();
         String[] parts = nombre.split(":");
         String part1 = parts[0];
         part1 = part1.trim();
         String part2 = parts[1];
         part2 = part2.trim();
         part1 = part1.toLowerCase();
         
         String pad = lblPad.getText();
         String[] parts2 = pad.split(":");
         String p2 = parts2[1];
         p2 = p2.trim();
         
         String info = "<<Datos Personales>>\n\n\n" + lblEdad.getText() +" años"+ "\n\n" + lblIMC.getText() + "\n\n\n"
                    +"<<Antecedentes>> \n\n\n"+ lblPP.getText() + "\n\n" + lblNP.getText() + "\n\n" + lblFam.getText() +
                    "\n\n" +lblMQ.getText()  + "\n\n\n <<Padecimiento>> \n\n\n" + p2;  
            
         String titulo = "Información del " + part1 +"\n\n" + part2;
            
         pdf.generarPDF(titulo, info, "VITA-DATA", "src/img/corazon.png", ruta+".pdf");       
         JOptionPane.showMessageDialog(null, "Creación de archivo PDF realizado correctamente", "Archivo PDF", 1);
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnImprimirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnImprimirKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImprimirKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatosPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimir;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblFam;
    private javax.swing.JLabel lblIMC;
    private javax.swing.JLabel lblMQ;
    private javax.swing.JLabel lblNP;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPP;
    private javax.swing.JLabel lblPad;
    // End of variables declaration//GEN-END:variables
}
